.gitignore, Vagrantfile, contracts/Staking.sol, contracts/StakingData.sol, contracts/UtilityToken.sol, contracts/UtilityTokenData.sol, contracts/compile.sh, dev/local-poa-geth.sh
[for review] updates from `cherrymint`
=> contracts: corrections to nonces and redeem comment

contracts/STPrime.sol
hold off until #5 is merged
before the registrar registers a core on the value chain it must verify that the genesis exactly specified TOKENS_MAX so that all base tokens are held by STPrime.
added modifier `onlyInitialized` to `claim`, `mint`, `burn` on STPrime.sol
fixes #6
=> ST' needs payable Initialize() to accept all base tokens

contracts/OpenSTUtility.sol
Correct `bytes23` to `bytes32`.
=> Contracts: fix type error in processRedeeming. Fixes #32.

test/OpenSTValue.js, test/OpenSTValue_utils.js
as branded tokens and ST both have a decimal precision of 18; and the conversion rate is `const uint256`; the minimal amount that can be redeemed is `conversionRate`;
addresses #3 
addresses #21
=> Redeem minimal amount

contracts/OpenSTValue.sol
for minimal precision of unstaking 1 ST Wei, we require minimum redemption amount to be required to be conversionRate UT Wei
fixes #39
=> minimum redemption amount required to conversionRate UT Wei

truffle.js
fixes #53 
this now produces the exact same gas consumption on in the integration test of openst-protocol as it does on the deployment tests of openst-platform on ropsten:
```
OpenSTValue.new                            2889358
OpenSTUtility.new                            4503101
```
=> truffle: enable 200 optimizer runs on tests

contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol, contracts/ProtocolVersioned.sol, test/Protocol.js, test/ProtocolVersioned.js, test/SimpleStake_integrated.js
Enable a very simple for of protocol transfer to begin with on 0.9.1 OpenSTValue and OpenSTUtility to transfer protocol. Addresses #36
=> Admin initiate and revoke protocol transfer

contracts/OpenSTUtility.sol, test/OpenSTUtility.js
Fixes #56 
Original proposal was to revert back the nonce on the utility chain (as monotonic nonce is kept on value chain); but the more elegant solution is to loosen the requirement on `redeem` and `redeemSTP` on `OpenSTUtility`;
as such a redeemer could redeem multiple times with the same nonce, but only one could be used to unstake, and as a result the redeemer only incurs a cost of handing over utility tokens on redeeming multiple times;
however if a redemption attempt fails, and is reverted, the redeemer can reuse the same nonce to retry the redemption.
addressed unit tests for this change in requirements.
=> On failed and reverted redemption, allow reuse of nonce

contracts/OpenSTUtility.sol, contracts/OpenSTUtilityInterface.sol, contracts/OpenSTValue.sol, contracts/OpenSTValueInterface.sol, contracts/Registrar.sol, test/OpenSTUtility.js, test/OpenSTValue.js
contracts, test: introduce fallback for process staking and redemption. fixes #26
this was forgotten to be merged into develop
=> Fallback for process Redemption and Staking

contracts/SimpleToken/MockToken.sol, test/MockToken.js
Add `MockToken.sol` which is an ops managed ERC20 token that borrows from SimpleTokenConfig and includes finalize functionality (as expected by deployment scripts) and `MockToken.js` to confirm the "mock" attributes and the finalize functionality.
Resolves #70.
=> Contracts: add and test MockToken.

contracts/SafeMathMock.sol, test/OpsManaged.js, test/OpsManaged_utils.js, test/Owned.js, test/Owned_utils.js, test/SafeMath.js
=> Import unit tests for Owned, OpsManaged and SafeMath

CHANGELOG.md, test/BrandedToken.js, test/MockToken.js, test/OpenSTUtility.js, test/OpenSTValue.js, test/Protocol.js, test/Registrar.js, test/Registrar_utils.js, test/STPrime.js, test/SimpleToken.js
PR for consistent use of Token units versus TokenWei units: review and correct unit tests for correct naming and use of Token vs TokenWei (ST vs STWei, BT vs BTWei, UT vs UTWei)
=> Unit tests: consistent use of Token units versus TokenWei units

contracts/OpenSTUtility.sol, contracts/OpenSTUtilityInterface.sol
Adds `public` visibility modifier to `mints` and `redemptions` and adds matching function signatures to `OpenSTUtilityInterface`. Does not lint, to minimize conflicts with #97.
Fixes #96.
=> Make mints and redemptions public

contracts/BrandedToken.sol, contracts/OpenSTUtility.sol, contracts/OpenSTUtilityInterface.sol, contracts/STPrime.sol, contracts/UtilityTokenAbstract.sol, contracts/UtilityTokenAbstractMock.sol, contracts/UtilityTokenInterface.sol, contracts/compile.sh, test/BrandedToken_utils.js, test/STPrime_utils.js, test/UtilityTokenAbstract.js, test/UtilityTokenAbstract_utils.js
✋  Merge **after** #100 is merged and this is rebased on `develop`.
For `UtilityTokenAbstract`:
- includes UUID params as constructor arguments (and makes attendant changes up through to `OpenSTUtility`)
- confirms that hash of UUID params matches UUID
- stores and exposes previously unexposed attributes of the UUID:  conversion rate, value chain ID, utility chain ID, and protocol address
🚨  `OpenSTUtility` has "a lot" of changes because the linter didn't like the order of functions (external before public, constructor before external)
Fixes #91.
=> UtilityTokenAbstract: construct with and expose UUID invariants

.travis.yml
Replace all recipients with "ci.report@ost.com"
=> Update travis notifications recipients

contracts/OpenSTUtility.sol, contracts/STPrime.sol, contracts/STPrimeConfig.sol, test/OpenSTUtility.js, test/STPrime_utils.js
Makes UUIDs iterable on utility chain:
- changes `registeredTokens` mapping visibility to public
- removes `registeredTokenProperties` in favor of auto-generated getter, `registeredTokens`—platform does not appear to use `registeredTokenProperties`
- inherits from the already-imported `STPrimeConfig`, strikes certain constants from `OpenSTUtility` in favor of those from `STPrimeConfig`, and attendant changes (the platform does use the auto-generated constant getters)
- adds a public state var, `uuids`, that's a dynamic `bytes32` array
- pushes UUIDs into the `uuids` array in `registerBrandedToken` (and in the constructor of `OpenSTUtility` for `STPrime`)
- adds function, `getUuidsSize`, to return size of `uuids`
Fixes #89
=> Make UUIDs iterable on utility chain

contracts/OpenSTValue.sol, test/OpenSTValue.js, test/Protocol.js
Make UUIDs iterable on value chain:
- changes `utilityTokens` mapping visibility to public
- adds a public state var, `uuids`, that's a dynamic `bytes32` array
- removes `utilityTokenProperties ` in favor of auto-generated getter, `utilityTokens `—platform does not appear to use `utilityTokenProperties`
- pushes UUIDs into the `uuids` array in `registerUtilityToken`
- adds function, `getUuidsSize`, to return size of `uuids`
Fixes #90
=> Make UUIDs iterable on value chain

contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol, test/OpenSTUtility.js, test/OpenSTUtility_utils.js, test/OpenSTValue.js, test/OpenSTValue_utils.js, test/Protocol.js, test/Registrar.js
Per handover instructions:
- updates unit tests for redeem/unstake
- updates integration tests for redeem/unstake
- include `unlockSecret` in ProcessedX events (platform will need to be notified of these changes)
=> Hashlock handover: update tests for redeem/unstake, add unlockSecret to events

test/MockToken.js
`truffle test MockToken.js` ->
Contract: MockToken
Basic properties
1) "before all" hook
Finalize
2) "before all" hook
0 passing (144ms)
2 failing
1) Contract: MockToken Basic properties "before all" hook:
`Error: MockToken contract constructor expected 0 arguments, received 4
at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:390:1
at new Promise (<anonymous>)
at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:374:1
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7) `
2) Contract: MockToken Finalize "before all" hook:
`Error: MockToken contract constructor expected 0 arguments, received 4
at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:390:1
at new Promise …
=> test:mocktoken.js removed 4 arguments from Mocktoken() constructor

contracts/proof/RLP.sol
Solution is to use strictly typed variables
=> [MOSA-96] - RLP.sol - Use of the "var" keyword is deprecated

contracts/Gate.sol
Resolves issue: #170 
Fixed typo in Gate::processStaking. `stakeAddress` was incorrectly named as `stakerAddress`
Ref: MOSA-124
=> Fixed typo in Gate:processStaking. MOSA-124

contracts/Core.sol
- Removed event ProofVerificationSkipped 
- Removed parameter hashedAccount from event signature of OpenSTProven      
- Added parameter wasAlreadyProved in event signature of OpenSTProven
=> [MOSA-129] Replace OpenSTProven and ProofVerificationSkipped events by OpenSTProven with additional parameter	

contracts/Gateway.sol, test/Gateway.js, test/Gateway_utils.js
Implements `setWorkers` function in Gateway contract, can be only called by owner.
Includes the setWorker test case.
ref: MOSA-30
fixes: #186
=> Add setWorkers function in gateway contract. MOSA-30

.gitattribute
GitHub uses linguist to enable language-related features. According to
linguist’s maintainers, the .sol file extension is too generic to assign
to Solidity.
As a solution the mapping is added to the `.gitattribute` file.
According to
https://medium.com/@danielque/psa-how-to-fix-githubs-syntax-highlighting-for-solidity-4e9867c540b6
Fixes #214
=> GitHub Syntax Highlighting for Solidity

SOLIDITY_STYLE_GUIDE.md
The solidity style guide now includes instructions on how to document
structs and mappings. Othere Solidity projects seem to not do this, so
it was not possible to adhere to a community standard.
Instead, I compared how rust and golang recommend to do it and chose the
rust way of documenting structs and mappings.
In golang, a struct's field would be documented on the same line after
the name.
I used `/** */` instead of `///` as our style guide explicitly says to
avoid `///`.
=> Added docs specification for structs and maps

SOLIDITY_STYLE_GUIDE.md
`@return` indentation should equal that of `@param`.
Fixes #236
=> Indentation of @return multiline is now correct

.travis.yml
If the target branch starts with the sequence `feature/`, then Travis
will build any pull request against it.
Fixes #242
=> Travis now builds all feature branch PRs

contracts/OpenSTValue.sol
Changes reference from "tx.origin" to "staking account" in `@dev` documentation comment for `stake`.
Resolves #233.
=> Update description of OpenSTValue.stake to reflect changes in 0.9.3

contracts/core/AuxiliaryCore.sol, contracts/core/AuxiliaryCoreConfig.sol, contracts/core/AuxiliaryCoreInterface.sol, contracts/core/OriginCore.sol, contracts/core/OriginCoreInterface.sol, test/core/AuxiliaryCore.js
An AuxiliaryCore contract tracks state roots of Ethereum at their
respective heights.
The cost to report a state root must be paid in the base token of the
auxiliary chain. This should prevent noise in the reports.
A state root can only be reported once per height.
Fixes #258
=> An origin state root can be reported to auxiliary

contracts/core/AuxiliaryStake.sol, test/core/AuxiliaryStake.js
The contract is initialised on auxiliary with a starting set of
validators. The starting set consists of addresses and their deposit.
All starting validators are assumed to join the validator set at height
0 and to not have left the set of validators, yet. The stake must be
greater than zero, otherwise it is irrelevant.
The contract also tracks the total stakes at any given height so it is
known what the weight of a validator is at a given height in comparison
to the total stake.
Fixes #270
=> Constructing the auxiliary stake contract

contracts/gateway/Core.sol
When a core is deployed on origin, the address of the related core on
the auxiliary chain should be set. That way, the getter can be used to
get the co-core address from the core.
=> Added the Co-Core variable and setter to the core

contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol
Extend long and short waits to the relevant chain equivalents of 3 weeks and 3 days.
Tests do not need to be updated because they use mocks to set the periods to sensible durations for testing.
=> Extend blocks to wait

contracts/core/AuxiliaryStake.sol, test/core/AuxiliaryStake.js, test/core/TestAuxiliaryStake.sol, test/lib/RevertProxy.sol
The OSTblock gate contract is allowed to update the OSTblock on the
auxiliary stake contract. It increases the OSTblock height and adds the
new validators.
The address of the OSTblock gate is set on construction and cannot be
changed later.
It is currently not allowed to remove validators. That will be added in
a later step and requires stitching with forward and rear validator sets
like described in the Casper FFG paper.
Refactored adding of new validators into a private method as it is used
when updating an OSTblock as well as on construction.
Added JavaScript tests to assert the correct behaviour when initialising
an auxiliary stake contract.
Added Solidity tests to test the actual update method. In order to test
for reverts, I added a revert proxy as described in the truffle …
=> New validators are now added at new OSTblocks

contracts/gateway/GatewayBase.sol
Following items are implemented. 
1. The organization can change bounty. 
2. For inbox messages, the bounty validation should be done from inbox active process. 
Note : Timelock period for change bounty is not implemented.
=> Inbox nonces and set bounty

contracts/core/BlockStore.sol, contracts/core/OriginCore.sol, contracts/core/PollingPlace.sol, contracts/core/Stake.sol
I replaced all mathematical operations with calls to SafeMath functions.
Exceptions were the loop variables in for loops where the biggest number
is limited by an array length.
Example:
`for (uint256 i = 0; i < anArray.length; i++)`
It is clear that `i` will never overflow.
Fixes #351
=> Core now uses SafeMath everywhere

contracts/core/OriginCore.sol, contracts/core/OriginCoreInterface.sol, contracts/lib/MetaBlock.sol, test/core/origin_core/constructor.js, test/core/origin_core/getAccumulatedGasTarget.js, test/core/origin_core/get_accumulate_gas_target.js, test/core/origin_core/propose_block.js, test/gateway/eip20gateway/helpers/eip20gateway.js
This PR fixes #383
- added `maxAccumulateGasLimit` variable  in `OriginCore`.
- added `_maxAccumulateGasLimit` in `OriginCore` constructor params.
- added function `getAccumulateGasTarget` in `OriginCore`.
- added function `getAccumulateGasTarget` in `OriginCoreInterface`.
function `getAccumulateGasTarget` calculated the accumulated gas target by adding `maxAccumulateGasLimit` to the accumulated gas of current committed meta-block.
Please note: A commit meta-block function is not implemenented yet, the test cases should be updated later.
=> Core should have getter for gas target [383]

contracts/gateway/EIP20CoGateway.sol, contracts/gateway/EIP20Gateway.sol, test/gateway/eip20_gateway/stake.js
Please merge #512 before this. 
Stake and redeem now supports zero gas price and gas limit. 
Fixes #494 
Unit test cases for `redeem` will be done in #517
=> Support zero gas price and gas limit in stake & redeem

package.json
Fixes #565  
Upgraded package.json version to `0.9.4` and name to `mosaic-contracts`
=> Upadte package json version to 0.9.4

.gitignore, .travis.yml, dist/index.js, package.json, tools/build_package.js
`package.json`:
I added the entries `main` and `files` in order to specify the entry
point and which files should be part of the package. Only `dist` is
required, as it contains the `main` and the data in a JSON file.
I also added `scripts.prepare` which will be run by NPM as first action
when you run `npm publish`.
I set the versdion to `0.10.0-alpha`, as the current contents are not
`0.9.4` anymore.
I created a new script `tools/build_package.js`, which reads a specified
set of contracts from the truffle build directory and adds the ABIs and
BINs of the specified contracts to a single object, which is serialized
to `dist/contracts.json` and read by `dist/index.js`.
For now, `dist/index.js` only reads the JSON file and exports the
object.
I added the built JSON file to `.gitignore`. It …
=> Provides NPM package to access contracts' metadata

contracts/gateway/EIP20CoGateway.sol, contracts/gateway/EIP20Gateway.sol, test/gateway/eip20_cogateway/progress_redeem_with_proof.js, test/gateway/eip20_gateway/progress_stake_with_proof.js
FIXES #409 
Waiting for #578 being merged.
=> Return penalty to staker if target chain has already progressed

contracts/gateway/EIP20CoGateway.sol, contracts/gateway/EIP20Gateway.sol, test/gateway/eip20_cogateway/confirm_revert_stake_intent.js, test/gateway/eip20_gateway/confirm_revert_redeem_intent.js
Fixes #662  partially
In order to follow best practices, any state change like deletion should happen before any external call. 
Though confirm revert stake intent and confirm revert redeem intent doesn't make any external call, its good practice to move state changeup in the method.
=> Rearrange deletion of structs in confirm revert stake intent and confirm revert redeem intent

contracts/gateway/EIP20CoGateway.sol, contracts/gateway/EIP20Gateway.sol, test/gateway/eip20_cogateway/confirm_stake_intent.js, test/gateway/eip20_gateway/confirm_redeem_intent.js, test/gateway/eip20_gateway/progress_unstake.js, test/gateway/eip20_gateway/progress_unstake_with_proof.js
Fixes #662 partially
Confirm stake intent and confirm redeem intent now checks `amount` > `maxRewardAmount`
ℹ️ Three tests are intentionally skipped because they were failing. To fix those tests proof needs to be generated again which doesn't break this new condition. Added ticket to track this. Refer #665
=> Add max reward check in confirm message

contracts/gateway/GatewayBase.sol, contracts/test/gateway/TestGatewayBase.sol, test/gateway/gateway_base/bounty_change.js
PR contains following :-
1. `BOUNTY_CHANGE_UNLOCK_PERIOD` constant is set to value which will enable to unlock bounty change period to 7-days.
2. Updated test-cases.
3. Added test-case to verify the unlock period in contract is set to the expected value.
Partially fixes :- #662
=> Bounty change unlock period in block height is set to 7-days.

contracts/gateway/GatewayBase.sol
Fixes #689 
Gateway base should be more general, it should talk about messages, not of the specific type of messages like stake or redeem.
=> Removed stake and redeem terminology from the gateway base

contracts/gateway/GatewayBase.sol
Fixes #699 
Replaced `_gasConsumed` to `_gasUsedDuringConfirmMessage` and `totalGasConsumed_` to `totalGasUsedInMessageTransfer_`
=> Improved variable names in GateawayBase.feeAmount()

contracts/gateway/OSTPrime.sol, contracts/gateway/UtilityToken.sol, contracts/test/gateway/MockUtilityToken.sol, contracts/test/gateway/TestOSTPrime.sol, contracts/test/gateway/TestUtilityToken.sol
Cast `token`/`_token` as `address` instead of `EIP20Interface` in `UtilityToken` and related contracts.
✏️N.B.: There will be conflicts with #710.
Resolves #702.
=> Contracts: type token as address in UtilityToken

.travis.yml
In an effort to speed up the travis ci build:
* installation of node/npm is done based on `node_js`
* `npm ci` is the default npm installation command
* truffle compilation is done automatically
=> Remove redundant commands from travis file

test_integration/02_stake_and_mint/04_stake_and_mint_after_revert.js
This PR adds integration testing to show that Stake and mint can be progressed when the message status of outbox is `DeclaredRevocation`.
Resolves #737.
=> Test: progress stake and mint after revert

contracts/gateway/ComposerInterface.sol, contracts/gateway/EIP20Gateway.sol, contracts/gateway/EIP20GatewayInterface.sol, contracts/gateway/GatewayBase.sol, contracts/gateway/StakerProxy.sol, contracts/test/gateway/SpyEIP20Gateway.sol, contracts/test/gateway/SpyToken.sol, test/gateway/staker_proxy/constructor.js, test/gateway/staker_proxy/stake.js, test/gateway/staker_proxy/transfer_token.js
A new staker proxy contract to stake on the gateway.
Temporarily added a composer interface to be able to call `removeStakerProxy`.
See also comment on https://github.com/OpenST/mosaic-contracts/issues/742.
Added unit tests for the proxy's methods.
Added new test doubles to ease writing of unit tests.
Fixes #741
=> Staker proxy

test/lib/merkle_patricia_proof.js
Tests all cases in parallel using `Promise.all`.
Fixes #719
=> Add test case that tests all generated proofs

contracts/gateway/OSTComposer.sol, contracts/gateway/StakerProxy.sol, test/gateway/staker_proxy/stake.js
PR covers below:
- Remove a check for a valid nonce from StakerProxy.stake()
- Replace StakerProxy's own implementation of a mutex by inheriting from Mutex contract.
- Remove mutex from OSTComposer::acceptStakeRequest function.
- Remove mutex from OSTComposer::revokeStakeRequest and OSTComposer::rejectStakeRequest
Fixes #763
=> Mutex refactoring and nonce removal check from StakerProxy.stake()

contracts/gateway/OSTComposer.sol, contracts/test/gateway/TestOSTComposer.sol, package.json, test/gateway/ost_composer/accept_stake.js, test/gateway/ost_composer/reject_stake_request.js, test/gateway/ost_composer/remove_staker_proxy.js, test/gateway/ost_composer/request_stake.js, test/gateway/ost_composer/revoke_stake_request.js
- Updates test cases accordingly.
- Adds `npm run update` script to ease updating submodules and npm
packages after switching branches.
Fixes: #772
=> Removes activeStakeRequestCount from OSTComposer

contracts/gateway/OSTComposer.sol, contracts/gateway/StakerProxy.sol, contracts/test/gateway/MockStakerProxy.sol, test/gateway/ost_composer/destruct_staker_proxy.js, test/gateway/staker_proxy/self_destruct.js
fixes #771 
This PR updates the flow of self-destructing staker proxy contract. With this PR, staker(owner) can call `destructStakerProxy` on composer contract.
This PR also delete ComposerInterface used in stakerProxy contract as there is no method call from staker proxy to composer.
=> Destructing staker proxy via ost composer contract

contracts/gateway/OSTComposer.sol, contracts/test/gateway/TestOSTComposer.sol, test/gateway/ost_composer/accept_stake.js, test/gateway/ost_composer/helpers/composer_utils.js, test/gateway/ost_composer/reject_stake_request.js, test/gateway/ost_composer/request_stake.js, test/gateway/ost_composer/revoke_stake_request.js
- stakeRequests mapping has been updated to
```mapping(bytes32 => bool) public stakeRequests```
- StakeRequest objects contract's storage optimization
- Below method interfaces has been updated so that stakeRequestHash can be calculated: 
- acceptStakeRequest()
- revokeStakeRequest()
- rejectStakeRequest()
Please see detailed gas analysis in the ticket.
Fixes #770
=> OSTComposer StakeRequest object storage optimization

README.md, package.json
- Changed repository clone URL to `HTTPS`
- Change `npm install` command instructions in README to `npm run update`.
- Rename `npm run compile-all` to `npm run compile:all`.
- `npm run compile:all` now compiles typescript files used during tests.
=> `npm run update` does not install deps of submodules

package.json
Fixes the travis tests.
Updated package.json
`postinstall` command was using `npm run compile-all` instead of `npm run compile:all`.
=> Updated package.json postinstall script

contracts/gateway/EIP20GatewayInterface.sol, contracts/gateway/OSTComposer.sol, contracts/gateway/StakerProxy.sol, contracts/test/gateway/SpyEIP20Gateway.sol, test/gateway/ost_composer/accept_stake.js, test/gateway/ost_composer/reject_stake_request.js, test/gateway/ost_composer/request_stake.js, test/gateway/ost_composer/revoke_stake_request.js, test/gateway/staker_proxy/stake.js
PR changes `valuetoken` variable name to `token` because deployed gateway contracts has `token` named variable which means value token address.
It also adds staker proxy address in `StakeRequested` event.
Reviewer can suggest better approach.
=> OSTComposer bug fixes
