contracts/Hasher.sol, contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol, contracts/STPrime.sol
=> Update master with reworked protocol

contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol
=> Complete redemption on OpenST Value and Utility

contracts/OpenSTValue.sol
=> correct assert on OpenSTValue.processStaking

test/Protocol.js
=> Rebased gh42 assert events in integration tests

contracts/OpenSTValue.sol, contracts/OpenSTValueInterface.sol
Adds `public` visibility modifier to `stakes` and `unstakes` and adds matching function signatures to `OpenSTValueInterface`. Plus linting.
Fixes #95.
=> Make stakes and unstakes mappings public

contracts/BrandedToken.sol, contracts/Hasher.sol, contracts/OpenSTUtility.sol, contracts/OpenSTUtilityInterface.sol, contracts/OpenSTValue.sol, contracts/OpenSTValueInterface.sol, contracts/Registrar.sol, contracts/STPrime.sol, contracts/STPrimeConfig.sol, contracts/UtilityTokenAbstract.sol, contracts/UtilityTokenAbstractMock.sol, contracts/UtilityTokenInterface.sol, test/BrandedToken_utils.js, test/OpenSTUtility.js, test/OpenSTValue.js, test/Protocol.js, test/Registrar.js, test/STPrime_utils.js, test/UtilityTokenAbstract.js, test/UtilityTokenAbstract_utils.js
This includes the following issue: 
https://github.com/OpenSTFoundation/openst-protocol/issues/107
=> conversion rate be a (bound) rational number

CHANGELOG.md
Updates `Changelog` for v0.9.2.
Relates to #114.
=> Update Changelog for v0.9.2.

contracts/Gate.sol
Adds gate contract
* gate contract is ProtocolVersioned
* declares a struct StakeRequest
* defines a mapping between staker address and StakeRequest 
* declares state variable workers
=> Add gate contract 

.gitignore, .travis.yml, contracts/Gate.sol, contracts/OpenSTValueInterface.sol, package-lock.json, package.json
This includes: 
1. requestStake implementation
2. revertStakeRequest implementation
3. rejectRequest implementation.
=> Gate contract: requestStake, revertStakeRequest and rejectStakeRequest implementation 

contracts/Workers.sol
* Adds the workers contract from the [openst-payments](https://github.com/OpenSTFoundation/openst-payments) repository.
* Sets an EIP20 token address in the contract constructor.
* Adds the functionality for calling the approve function for an address on an EIP20 token.
MOSA-27
=> Adds the workers contract

contracts/Gate.sol, contracts/Workers.sol, contracts/WorkersInterface.sol, package-lock.json, test/Gate.js, test/Gate_utils.js
This PR includes the following:
**MOSA-26:** Interface workers
**MOSA-32:** Story request stake
**MOSA-33:** Story request stake reject
**MOSA-34:** Story request stake revert
**MOSA-35:** Story revert stake
**MOSA-36:** Story revert stake hunter (non whitelisted worker)
And Story Process staking
=> Worker Integration and test updates

contracts/proof/MerklePatriciaProof.sol, contracts/proof/RLP.sol, contracts/proof/util.sol
MerklePatriciaProof.sol
RLP.sol
util.sol
=> Adding Proof library contracts

.travis.yml
Enable travis build for branch V.0.9.3/develop
=> Sarvesh/enable build on travis for v.0.9.3

contracts/Workers.sol
* Added comments on the new function
* Removed some older comments.
=> Workers contract comments

test/Gate_utils.js
Updated test for Gate, now passing proper stakingAccount. MOSA-120.
**_Question: Will SimpleToken Prime be gated?_**
If yes then I will need to incorporate one more test case.
=> Gate: correct test w/r/t stakingAccount. MOSA-120

contracts/Gate.sol, test/Gate.js
Resolves issue: #168 
- Removed the whitelisted worker check
- Updated the corresponding test cases.
Ref: _MOSA-121_
=> Removed check if whitelisted worker in Gate::processStaking. MOSA-121

contracts/Gateway.sol, test/ContractStructureTest.js, test/Gateway.js, test/Gateway_utils.js
Updated all references of `Gate` to say `Gateway`.
Gh: #181
Ref: _MOSA-141_
=> Update all references to Gate to be Gateway. MOSA-141

contracts/Core.sol, contracts/Hasher.sol, contracts/MerklePatriciaProof.sol, contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol, contracts/SimpleToken/ERC20Token.sol, contracts/SimpleToken/MockToken.sol, contracts/SimpleToken/SimpleToken.sol, contracts/UtilityTokenAbstractMock.sol, contracts/truffle/Migrations.sol
Fixed all the compilation warnings.
fixes: #188 
ref: MOSA-52
=> Resolve all the compiler warnings after upgrading to solidity 0.4.23 [MOSA-52]

contracts/OpenSTValue.sol, test/OpenSTValue.js
- Add stakingAccount condition in processStaking and revertStaking
- Add test cases for processStaking and revertStaking
resolves issue #192
=> enforce stakingAccount on OpenSTValue processStaking and revertStaking

CHANGELOG.md
Updates Changelog to reflect v0.9.3.
=> Release: update changelog for v.0.9.3 [MOSA-137]

contracts/OpenSTUtility.sol, contracts/OpenSTValue.sol
_resolves_: #210 
_ref_: MOSA-46
=> Use generic object name in OpenSTValue and OpenSTUtility protocol transfer functions. MOSA-46. GH-210

SOLIDITY_STYLE_GUIDE.md
`@return` and `@param` now have the same style. One tag per variable and
alignment per tag.
=> Return parameters are now the same as arguments

test/gateway/MockToken.js
=> Unit tests for uncovered lines in MockToken.sol

contracts/Registrar.sol, test/Registrar.js
=> Hunter changes

contracts/OpenSTValue.sol, test/OpenSTValue.js, test/OpenSTValue_utils.js
Adds and test deactivate function.
=> Add deactivate function to OSTV

contracts/core/AuxiliaryCore.sol, contracts/core/AuxiliaryCoreConfig.sol, contracts/core/AuxiliaryCoreInterface.sol, test/core/AuxiliaryCore.js
The method is not payable anymore and the respective tests have been
removed.
Fixes #267
=> It costs no fee anymore to report an origin block

.gitignore, contracts/test/test_lib/KeyValueStoreStub.sol, test/lib/TestMessageBus.sol
Fixes #330 
positive tests for
ProgressInbox
DeclareRevocationMessage
ChangeInboxState
ChangeOutboxState
=> MessageBus Testing

migrations/2_deploy_contracts.js
Fixed issues caused by truffle 5
=> Removed unused migration , removed assert deploy and link

.travis.yml, package.json
This pull request contains the following changes.
- Updated .travis.yml to include `npm run compile`
- Removed the sleep 10s
- Updated package.json to include `truffle compile` in the scripts.
fixes: #519
=> Fix travis test.

contracts/lib/Organized.sol, test/lib/organized/constructor.js, test/test_lib/utils.js
⚠️ First review and merge #513 ⚠️
Fixes #485
=> Added Organized and accompanying tests

package.json, tools/build_package.js
=> Added OSTPrime to npm package

CHANGELOG.md
=> Change for v0.10.0

CHANGELOG.md, package.json
* Added a release description
* Reordered the change log
* Updated keywords of `package.json`
* Updated version of `package.json`
* License is now valid SPDX expression
Fixes #645
=> Prepare release 0.10.0-beta.1

contracts/lib/BytesLib.sol, contracts/lib/MessageBus.sol
Fixes #662  partially
This PR is about removing dead code from Messagebus and Bytes lib
=> removed dead code from message bus and bytes lib

contracts/lib/MessageBus.sol
=> Fixed comment in messagebus

proof_generation/helper/co_gateway.js, proof_generation/helper/gateway.js, test_integration/02_stake_and_mint/01_stake_and_mint.js, test_integration/02_stake_and_mint/02_stake_and_mint_proof.js, test_integration/02_stake_and_mint/utils/progress_mint_assertion.js, test_integration/02_stake_and_mint/utils/progress_stake_assertion.js
fixes: #607 
This PR Includes the integration test for stake and mint with proof.
=> Stake & Mint integration tests with proof

test_integration/02_stake_and_mint/02_stake_and_mint_proof.js
Quick fix for failing the test.
Two PR's were pushed to develop branch, code changes from one branch caused the test fail in the other branch. 
Took the latest develop branch and fixed the issue on this PR.
=> Fixed breaking test

package-lock.json
fixes #174 
This PR fixes high and medium severity npm vulnerabilities. Some low severity can't be fixed because of fix is not available.
=> Fixed vulnerablities

contracts/gateway/EIP20Gateway.sol, package-lock.json, package.json, test_integration/docker.js, test_integration/main.sh
References https://github.com/OpenST/mosaic-contracts/issues/758
=> Update truffle dependency

.gitignore, .travis.yml, package-lock.json, package.json, ts-generator.json
=> Autogenerate contract interacts using typechain/ts-generator

CHANGELOG.md, tools/build_package.js, tsconfig.json
#794 
This PR adds redeem pool and proxy contract to build script.
=> Build redeem pool and redeem proxy contract
